POST http://localhost:3001/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzQ2OTAzMjFlNzc2NGY4MDM4OGIzZSIsInVzZXJuYW1lIjoid2F0c29uIiwiaWF0IjoxNjE4Mjc4ODI5fQ.qpcBpGAbljuyu_uGTUQzvdQBFn_Jxs43SnAbRGJRjAM

{
  "name": "El camino de los reyes",
  "author": "Brandon Sanderson",
  "saga": "El archivo de las tormentas",
  "number": 1
}