PUT http://localhost:3001/books/606b386d3559187edc6ba7ec
content-type: application/json

{
  "name": "Juramentada",
  "author": ["Brandon Sanderson"],
  "saga": "El Archivo De las tormentas",
  "number": 3
}